#!/usr/bin/env python3
# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0
"""Helpers for rendering generated C++ files."""

from __future__ import annotations

from collections.abc import Iterable


def escape_cpp_string(text: str) -> str:
    """Escape a string for a C++ string literal."""
    return text.replace("\\", "\\\\").replace('"', '\\"')


def cpp_u32_string_literal(text: str, *, chunk_size: int = 96) -> list[str]:
    """Render a UTF-32 C++ string literal as one or more source lines."""
    if not text:
        return ['U""']
    result: list[str] = []
    for start in range(0, len(text), chunk_size):
        result.append(f'U"{escape_cpp_string(text[start:start + chunk_size])}"')
    return result


def cpp_byte_string_literal(byte_values: Iterable[int], *, chunk_size: int = 64) -> list[str]:
    """Render byte values as one or more C++ string literal source lines."""
    values = list(byte_values)
    if not values:
        return ['""']
    result: list[str] = []
    for start in range(0, len(values), chunk_size):
        chunk = values[start:start + chunk_size]
        result.append('"' + "".join(f"\\x{value:02X}" for value in chunk) + '"')
    return result


def generated_cpp_source(generator: str, summary_lines: list[str], body_lines: list[str]) -> str:
    """Create a complete generated C++ source file.

    Dense generated tables are surrounded by clang-format guards. The repository still runs clang-format over these
    files, but the byte-for-byte generator check remains stable afterwards.
    """
    lines = [
        "// Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev",
        "// SPDX-License-Identifier: Apache-2.0",
        "// clang-format off",
        "//",
        f"// This file is generated by {generator}",
    ]
    if summary_lines:
        lines.append("//")
        lines.extend(f"// {line}" for line in summary_lines)
    lines.extend(body_lines)
    lines.extend(["// clang-format on", ""])
    return "\n".join(lines)


def generated_cpp_header(generator: str, summary_lines: list[str], body_lines: list[str]) -> str:
    """Create a complete generated C++ header file with passive data only."""
    lines = [
        "// Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev",
        "// SPDX-License-Identifier: Apache-2.0",
        "// clang-format off",
        "//",
        f"// This file is generated by {generator}",
    ]
    if summary_lines:
        lines.append("//")
        lines.extend(f"// {line}" for line in summary_lines)
    lines.extend(["#pragma once", ""])
    lines.extend(body_lines)
    lines.extend(["// clang-format on", ""])
    return "\n".join(lines)
