#!/usr/bin/env python3
# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0
"""Generate the console Unicode width lookup table from checked-in UCD data."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


LIBRARY_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = LIBRARY_ROOT / "utilities" / "data" / "unicode"
OUTPUT_PATH = LIBRARY_ROOT / "src" / "erbsland" / "cterm" / "impl" / "UnicodeWidthTable.cpp"
UNICODE_LIMIT = 0x110000


@dataclass(frozen=True)
class Range:
    begin: int
    end: int


def parse_code_point_range(text: str) -> Range:
    field = text.strip()
    if ".." in field:
        begin_text, end_text = field.split("..", maxsplit=1)
        return Range(int(begin_text, 16), int(end_text, 16))
    value = int(field, 16)
    return Range(value, value)


def iter_data_lines(path: Path):
    with path.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.split("#", maxsplit=1)[0].strip()
            if line:
                yield line


def apply_range(widths: bytearray, entry_range: Range, width: int) -> None:
    widths[entry_range.begin : entry_range.end + 1] = bytes([width]) * (entry_range.end - entry_range.begin + 1)


def load_widths() -> bytearray:
    widths = bytearray([1]) * UNICODE_LIMIT

    east_asian_width_path = DATA_DIR / "EastAsianWidth.txt"
    for line in iter_data_lines(east_asian_width_path):
        code_point_text, width_class = [part.strip() for part in line.split(";", maxsplit=1)]
        if width_class not in {"W", "F"}:
            continue
        apply_range(widths, parse_code_point_range(code_point_text), 2)

    unicode_data_path = DATA_DIR / "UnicodeData.txt"
    for line in iter_data_lines(unicode_data_path):
        fields = line.split(";")
        code_point = int(fields[0], 16)
        general_category = fields[2]
        if general_category.startswith("M") or general_category in {"Cc", "Cf"}:
            widths[code_point] = 0

    return widths


def compress_widths(widths: bytearray) -> list[tuple[int, int, int]]:
    ranges: list[tuple[int, int, int]] = []
    begin = 0
    current_width = widths[0]
    for code_point in range(1, UNICODE_LIMIT):
        if widths[code_point] == current_width:
            continue
        ranges.append((begin, code_point - 1, current_width))
        begin = code_point
        current_width = widths[code_point]
    ranges.append((begin, UNICODE_LIMIT - 1, current_width))
    return ranges


def write_output(ranges: list[tuple[int, int, int]]) -> None:
    lines = [
        "// Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev",
        "// SPDX-License-Identifier: Apache-2.0",
        "//",
        "// This file is generated by erbsland-cpp-color-term/utilities/generate_unicode_width_table.py",
        "#include \"UnicodeWidth.hpp\"",
        "",
        "#include <array>",
        "",
        "",
        "namespace erbsland::cterm::impl {",
        "",
        "",
        "auto charWidthTable() noexcept -> std::span<const CharWidth> {",
        f"    static constexpr auto cTable = std::array<CharWidth, {len(ranges)}>{{{{",
    ]

    for begin, end, width in ranges:
        lines.append(f"        CharWidth{{0x{begin:06X}U, 0x{end:06X}U, {width}U}},")

    lines.extend(
        [
            "    }};",
            "    return cTable;",
            "}",
            "",
            "",
            "}",
            "",
        ]
    )
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    widths = load_widths()
    ranges = compress_widths(widths)
    write_output(ranges)


if __name__ == "__main__":
    main()
