#pragma once
#include "../../../../src/erbsland/cterm/text/TextNodeType.hpp"
// !!! WARNING - THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the `generate_header_files.py` script.

