// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once
// !!! WARNING - THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the `generate_header_files.py` script.


#include "Alignment.hpp"
#include "Anchor.hpp"
#include "AxisMapper.hpp"
#include "Coordinate.hpp"
#include "Direction.hpp"
#include "Margins.hpp"
#include "Orientation.hpp"
#include "Position.hpp"
#include "Rectangle.hpp"
#include "Size.hpp"


