#!/usr/bin/env python3
# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0
"""Generate the checked-in embedded HTML source file for the profiling executable."""

from __future__ import annotations

import argparse
from pathlib import Path


PROFILE_DIR = Path(__file__).resolve().parent.parent
INPUT_PATH = PROFILE_DIR / "data" / "test-document.html"
OUTPUT_PATH = PROFILE_DIR / "src" / "EmbeddedHtml.cpp"


def escape_cpp_string(text: str) -> str:
    escaped = []
    for character in text:
        if character == "\\":
            escaped.append("\\\\")
        elif character == "\"":
            escaped.append("\\\"")
        elif character == "\n":
            escaped.append("\\n")
        elif character == "\r":
            escaped.append("\\r")
        elif character == "\t":
            escaped.append("\\t")
        else:
            escaped.append(character)
    return "".join(escaped)


def generate_source(document: str) -> str:
    lines = [
        "// Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev",
        "// SPDX-License-Identifier: Apache-2.0",
        "//",
        "// This file is generated by test/profiling/html-renderer/tools/generate_embedded_html.py",
        "#include \"EmbeddedHtml.hpp\"",
        "",
        "",
        "namespace profiling::htmlrenderer {",
        "",
        "",
        "static constexpr auto cEmbeddedHtmlText =",
    ]
    for raw_line in document.splitlines(keepends=True):
        lines.append(f"    \"{escape_cpp_string(raw_line)}\"")
    if not document:
        lines.append("    \"\"")
    lines.extend(
        [
            "    ;",
            "",
            "const std::string_view cEmbeddedHtml = cEmbeddedHtmlText;",
            "",
            "",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=INPUT_PATH, help="The HTML document to embed.")
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH, help="The generated C++ source file.")
    parser.add_argument("--check", action="store_true", help="Verify that the generated file is up to date.")
    return parser.parse_args()


def main() -> None:
    args = parse_arguments()
    document = args.input.read_text(encoding="utf-8")
    generated_source = generate_source(document)
    if args.check:
        existing_source = args.output.read_text(encoding="utf-8")
        if existing_source != generated_source:
            raise SystemExit("The embedded HTML source file is out of date.")
        return
    args.output.write_text(generated_source, encoding="utf-8")


if __name__ == "__main__":
    main()
